<<<<<<< HEAD
<<<<<<< HEAD
# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


apiVersion: 1

datasources:
  - name: Prometheus
    uid: webstore-metrics
    type: prometheus
    url: http://prometheus:9090
    editable: true
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: webstore-traces
          name: trace_id

        - url: http://localhost:8080/jaeger/ui/trace/$${__value.raw}
          name: trace_id
          urlDisplayLabel: View in Jaeger UI
=======
=======
>>>>>>> e3cfa673a16b249f79fbbe636908819d58b798d2
# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


apiVersion: 1

datasources:
  - name: Prometheus
    uid: webstore-metrics
    type: prometheus
    url: http://prometheus:9090
    editable: true
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: webstore-traces
          name: trace_id

        - url: http://localhost:8080/jaeger/ui/trace/$${__value.raw}
          name: trace_id
          urlDisplayLabel: View in Jaeger UI
<<<<<<< HEAD
>>>>>>> 9594cd0 (chore: verify github actions)
=======
>>>>>>> e3cfa673a16b249f79fbbe636908819d58b798d2
