<<<<<<< HEAD
<<<<<<< HEAD
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-demo
  labels:

    opentelemetry.io/name: opentelemetry-demo
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: opentelemetry-demo
    app.kubernetes.io/version: "1.12.0"
    app.kubernetes.io/part-of: opentelemetry-demo
=======
=======
>>>>>>> e3cfa673a16b249f79fbbe636908819d58b798d2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-demo
  labels:

    opentelemetry.io/name: opentelemetry-demo
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: opentelemetry-demo
    app.kubernetes.io/version: "1.12.0"
    app.kubernetes.io/part-of: opentelemetry-demo
<<<<<<< HEAD
>>>>>>> 9594cd0 (chore: verify github actions)
=======
>>>>>>> e3cfa673a16b249f79fbbe636908819d58b798d2
